---
# General Spring configuration
spring:
  output:
    ansi:
      enabled: always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

# Configuration for Logback.
logging:
  config: classpath:logback-dev.xml

